name: urwealthpal
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+20

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  fluttertoast: ^8.2.2
  fl_chart: any
  store_redirect: ^2.0.1
  pinput: any
  http: ^0.13.5
  flutter_dotenv: 5.0.2
  shared_preferences: 2.2.0
  get: 4.6.5
  flutter_html: ^2.1.2
  url_launcher : ^6.1.11
  image_picker : ^1.0.2
  device_info_plus : ^8.2.2
  in_app_purchase : ^3.1.8
  order_tracker : ^0.0.2
  permission_handler : ^11.0.1
  path_provider : ^2.1.0
  firebase_core : ^2.20.0
  firebase_messaging : ^14.7.2
  video_player : ^2.7.0
  file_picker : ^5.2.10
  webview_flutter : ^2.8.0
  flutter_share : ^2.0.0
  cached_network_image : ^3.2.3
  flutter_pdfview : ^1.3.2
  badges : any
  maps_launcher : ^2.2.0
  dio : ^5.4.1
  image_cropper : any
  auto_size_text : ^3.0.0
  local_auth : ^2.1.6


#  flutter_local_notifications: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - .env.dev
    - .env.prod

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
